"""
Django settings for mooder project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if os.path.exists(os.path.join(BASE_DIR, '.secretkey')):
    with open(os.path.join(BASE_DIR, '.secretkey'), 'rb') as f:
        SECRET_KEY = f.read()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django_markup',
    'pure_pagination',
    'bootstrap3',
    'captcha',
    #'accounts',
    'archives',
    'managements',
    'oauth_client',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mooder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'mooder.context.global_site_context',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mooder.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'mooder', 'static_cdn')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mooder', 'media_cdn')

AUTH_USER_MODEL = 'oauth_client.Member'

LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('archive:index')

# MARKDOWN_DEUX_STYLES = {
#     "default": {
#         "extras": {
#             "code-friendly": None,
#             "fenced-code-blocks": None,
#             "break-on-newline": None
#         },
#         "safe_mode": "escape",
#     },
# }

PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

MARKUP_SETTINGS = {
    'markdown': {
        'safe_mode': 'escape',
        'extensions': ('extra', 'nl2br', 'codehilite')
    }
}

USER_LEVEL_RANGE = (
    ((0, 30), ('level1', '落地成盒'), 'default'),
    ((30, 50), ('level2', '亚洲拳王'), 'default'),
    ((50, 100), ('level3', '平地翻车'), 'secondary'),
    ((100, 200), ('level4', '搜刮狂魔'), 'secondary'),
    ((200, 500), ('level5', '绝命快递'), 'primary'),
    ((500, 1000), ('level6', '钓鱼执法'), 'primary'),
    ((1000, 2000), ('level7', '幻影坦克'), 'success'),
    ((2000, 3000), ('level8', '厕所战神'), 'success'),
    ((3000, 6000), ('level9', '晚上吃鸡'), 'warning'),
    ((6000, 10000), ('level10', '内测元老'), 'warning'),
    ((10000, 18000), ('level11', '平底金锅'), 'warning'),
    ((18000, 30000), ('level12', '白裙大汉'), 'warning'),
    ((30000, -1), ('level13', '氪金大佬'), 'danger')
)

SITE = {
    'title': '61D团队贡献平台',
    'description': '一个团队使用的贡献平台',
    'keyword': '安全,团队,贡献'
}

ACCOUNT_ACTIVATION_DAYS = 3
REGISTRATION_AUTO_LOGIN = False
INCLUDE_AUTH_URLS = False
INCLUDE_REGISTER_URL = True
REGISTRATION_FORM = 'oauth_client.forms.SignupForm'

# 是否启用邮箱激活，False则需要管理员手工激活，True为邮箱激活
SEND_ACTIVATION_EMAIL = True

INTERNAL_IPS = ['127.0.0.1']
