version: '3.1'
services:
 web:
   build: .
   ports:
    - "127.0.0.1:8000:80"
    - "8080:8000"
   depends_on:
    - db
   env_file:
    - .env
   volumes:
    - file-data:/data
 db:
   image: mysql
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci 
   environment:
    - MYSQL_ROOT_PASSWORD=61disbest
    - MYSQL_USER=61d
    - MYSQL_PASSWORD=61d
    - MYSQL_DATABASE=oauth
   volumes:
    - db-data:/var/lib/mysql
volumes:
  file-data:
    driver: local
  db-data:
    driver: local
