# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:33
from __future__ import unicode_literals

import oauth_client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0002_auto_20161004_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to=oauth_client.models.generate_upload_filename, verbose_name='头像'),
        ),
    ]
